server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#zuul:
  #routes:
    #user-service: /user-service/**
    #user-service:
      #path: /user-service/**
      #url: http://127.0.0.1:8082
      #serviceId: user-service
spring:
  application:
    name: gateway
#zuul:
#  routes:
#    user-service:
#      path: /user/**
#      serviceId: user-service
#      strip-prefix: false
#  ignored-services:
#    - consumer-service
zuul:
  prefix: /api
  routes:
    user-service: /user/**
  ignored-services:
    - consumer-service
  #strip-prefix: false
